/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

class Employee{
    private String name;
    private int id;
    private String department;
    public Employee(String name, int id, String department){
        this.name = name;   
        this.id = id;
        this.department = department;
    }

public String toString() {
  return "ID"+id +"Name"+name + "dep"+department;  
}

}



public class App {
    static Map<Integer,Employee> empmap= new HashMap<>();
    static Scanner scanner =new Scanner(System.in);
    

    public static void main(String[] args) {
       int choice;

       
        do {
            System.out.println("\n--- Employee Management System ---");
            System.out.println("1. Add Employee");
            System.out.println("2. View All Employees");
            System.out.println("3. Delete Employee");
            System.out.println("0. Exit");
            System.out.print("Enter your choice: ");

            choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline

            switch (choice) {
                case 1 -> addEmployee();
                case 2 -> viewEmployees();
                case 3 -> deleteEmployee();
                case 0 -> System.out.println("Exiting...");
                default -> System.out.println("Invalid choice.");
            }
           
       } while (choice!=0);

    }

       static void addEmployee() {
      System.out.println("name"); 
      String name = scanner.nextLine();
      System.out.println("id");
      int id = scanner.nextInt();
      scanner.nextLine(); // Consume newline
      System.out.println("department");
      String department = scanner.nextLine();
      Employee emp = new Employee(name, id, department);
      empmap.put(id, emp);
      System.out.println("Employee added successfully!");
    }

    static void viewEmployees() {
        if (empmap.isEmpty()) {
            System.out.println("No employees found.");
        } else {
            System.out.println("\nEmployee List:");
            for (Employee emp : empmap.values()) {
                System.out.println(emp);
            }
        }
    }

    static void deleteEmployee() {
        System.out.print("Enter employee ID to delete: ");
        int id = scanner.nextInt();
        scanner.nextLine(); // Consume newline
        if (empmap.containsKey(id)) {
            empmap.remove(id);
            System.out.println("Employee deleted successfully.");
        } else {
            System.out.println("Employee not found.");
        }
    }
}

 
